import en, { type Messages } from './en';

const es: Messages = {
  ...en,
  seo: { title: (n) => `bestjev: ${n} proyectos Jev open source y herramientas`, description: (n) => `Explora ${n} proyectos Jev open source verificados en bestjev, incluidos SDK, agentes, integraciones, aplicaciones, benchmarks y herramientas para desarrolladores.`, catalogName: 'Catálogo de proyectos de código abierto bestjev', alternateName: 'Catálogo de proyectos Jev de bestjev', imageAlt: (p, c) => `${p} proyectos Jev de código abierto verificados en ${c} categorías` },
  nav: { close: 'Cerrar navegación', primary: 'Navegación principal', overview: 'Resumen', allProjects: 'Todos los proyectos', aboutBestjev: 'Acerca de bestjev', aboutJev: 'Acerca de Jev', categories: 'Categorías', projectCategories: 'Categorías de proyectos', collaborate: 'Enviar y colaborar', collaborateLabel: 'Enviar y colaborar', submit: 'Enviar', email: 'Correo', promote: 'Promociona tu proyecto', open: 'Abrir navegación', language: 'Idioma', home: 'Inicio de bestjev', logoAlt: 'Logotipo de bestjev', flagAlt: (language) => `Bandera del idioma ${language}`, githubRepository: 'Abrir el repositorio de bestjev en GitHub', xProfile: 'Seguir al responsable de bestjev en X', emailMaintainer: 'Enviar un correo al responsable de bestjev', promoteEmail: 'Enviar un correo a bestjev para promocionar un proyecto' },
  hero: { title: 'Los mejores proyectos Jev', summary: (p, c, l) => `Busca entre ${p} repositorios verificados de ${c} categorías y ${l} lenguajes.`, lastUpdated: 'Última actualización', updatedDate: '22 de septiembre de 2026', filterLanguage: 'Filtrar por lenguaje', allLanguages: 'Todos los lenguajes', languages: 'Lenguajes', addedToday: 'Añadidos hoy', addedThisWeek: 'Añadidos esta semana', clearRecency: 'Mostrar todas las fechas', searchPlaceholder: 'Buscar proyectos, lenguajes o decisiones', imageAlt: 'Las entradas estructuradas pasan por Jev y se convierten en decisiones probabilísticas' },
  filterPage: { categoryTitle: (category) => `Awesome ${category} Jev Projects`, categorySeoTitle: (category) => `Awesome ${category} Jev Projects | bestjev`, categoryDescription: (projects, category) => `Explora una selección awesome de ${projects} proyectos Jev open source verificados de ${category} en bestjev. Compara repositorios de GitHub, estrellas, lenguajes e implementaciones.`, todayTitle: 'Proyectos Jev añadidos hoy', todaySeoTitle: 'Nuevos proyectos Jev open source de hoy | bestjev', todayDescription: (projects) => `Descubre ${projects} proyectos Jev open source añadidos hoy a bestjev, con repositorios de GitHub, lenguajes, estrellas e implementaciones verificadas.`, weekTitle: 'Proyectos Jev añadidos esta semana', weekSeoTitle: 'Nuevos proyectos Jev open source de la semana | bestjev', weekDescription: (projects) => `Descubre ${projects} proyectos Jev open source añadidos esta semana a bestjev, con repositorios de GitHub, lenguajes, estrellas e implementaciones verificadas.` },
  catalog: { all: 'Todos', project: 'Proyecto', stars: 'Estrellas', language: 'Lenguaje', addedAt: 'Añadido', description: 'Descripción', projectsLabel: 'Proyectos Jev', sortAscending: 'Ordenar por estrellas ascendente', sortDescending: 'Ordenar por estrellas descendente', noMatches: 'No hay proyectos coincidentes', noMatchesHint: 'Prueba otra palabra clave o categoría.', showMore: 'Mostrar más proyectos' },
  siteIntro: { eyebrow: 'Sobre el catálogo', title: '¿Qué es bestjev?', paragraphs: ['bestjev es un directorio independiente y mantenido por la comunidad de proyectos de código abierto creados alrededor de Jev, el modelo System One de TypeSafe AI para decisiones tipadas.', 'Cada ficha enlaza al repositorio original y registra su categoría, lenguaje principal, una instantánea de estrellas de GitHub y una descripción localizada. Así, los desarrolladores pueden encontrar SDK, agentes, integraciones, aplicaciones, investigaciones y herramientas de Jev verificables.', 'bestjev no está afiliado ni respaldado por TypeSafe AI.'] },
  about: { title: '¿Qué es Jev?', paragraphs: ['Jev es el modelo System One de TypeSafe AI para decisiones que el software necesita consumir. En lugar de generar prosa libre, recibe un estado y preguntas tipadas y devuelve respuestas estructuradas con probabilidades calibradas.', 'Encaja en flujos donde las opciones o los criterios se conocen de antemano: enrutar un agente, validar una llamada a herramienta, ordenar candidatos, comprobar una política o decidir si una acción debe continuar.'], advantage: 'Ventaja operativa', advantageText: 'Las aplicaciones pueden establecer umbrales deterministas, inspeccionar la incertidumbre y dirigir los casos de baja confianza a una persona o a un modelo mayor.', primitives: [{ code: 'CHOICE', title: 'Elegir una opción', description: 'Selecciona entre un conjunto conocido y devuelve probabilidades con confianza.' }, { code: 'SCORE', title: 'Puntuar con una rúbrica', description: 'Sitúa una entrada en una escala ordenada y devuelve la distribución completa.' }, { code: 'NOUL', title: 'Estimar la verdad', description: 'Devuelve la probabilidad de que una afirmación sea cierta, entre cero y uno.' }] },
  methodology: { title: '¿Cómo se verifica este catálogo?', intro: 'Cada entrada se contrasta con pruebas públicas: el repositorio original, la documentación del proyecto y el uso visible de Jev. Las estrellas son una instantánea fechada, no una clasificación de calidad.', curatedBy: 'Selección de', quote: '“Piensa en Jev como una llamada a una función de inteligencia de frontera: entra estado no estructurado y salen decisiones probabilísticas tipadas.”', quoteSource: 'TypeSafe AI, presentación de Jev', sourcesTitle: '¿Qué fuentes utiliza bestjev?', officialDocs: 'Documentación oficial de Jev', officialDocsSuffix: ' para conceptos y primitivas del producto.', repositories: 'Repositorios públicos de GitHub', repositoriesSuffix: ' para pruebas de implementación y metadatos.', catalogData: 'Datos del catálogo legibles por máquinas', catalogDataSuffix: ' para registros de proyectos reproducibles.' },
  submission: { eyebrow: 'Colabora', title: 'Cómo enviar un proyecto nuevo', intro: 'Si conoces un proyecto público que utiliza Jev, envíanos su repositorio y las pruebas necesarias para verificarlo. Revisamos cada propuesta antes de publicarla en el catálogo.', shortCta: 'Enviar proyecto', cta: 'Enviar un proyecto', ctaHint: 'Abre un issue de GitHub con datos precompletados.', steps: [{ title: 'Comparte el repositorio', description: 'Incluye la URL pública de GitHub y una descripción breve de lo que hace el proyecto.' }, { title: 'Muestra cómo usa Jev', description: 'Enlaza código, documentación, una demo u otra fuente pública que permita verificar la integración con Jev.' }, { title: 'Revisamos y publicamos', description: 'Verificamos las pruebas, elegimos la categoría adecuada y añadimos los proyectos aceptados en una futura actualización.' }] },
  footer: { label: 'Información del sitio', about: 'Acerca de bestjev', contact: 'Contactar con bestjev', privacy: 'Política de privacidad', terms: 'Términos de uso', docs: 'Documentación oficial de Jev' },
};

export default es;
