import en, { type Messages } from './en';

const ko: Messages = {
  ...en,
  seo: { title: (n) => `${n}개 Jev AI 프로젝트, SDK 및 도구 | bestjev`, description: (n) => `TypeSafe AI의 System One 모델 Jev를 활용한 ${n}개 오픈소스 프로젝트, SDK, 에이전트, 통합, 벤치마크 및 도구를 검색하세요.`, catalogName: 'bestjev 오픈소스 프로젝트 카탈로그', alternateName: 'Awesome Jev 프로젝트 카탈로그', imageAlt: (p, c) => `${c}개 범주의 검증된 Jev 오픈소스 프로젝트 ${p}개` },
  nav: { close: '탐색 닫기', primary: '기본 탐색', overview: '개요', allProjects: '모든 프로젝트', aboutBestjev: 'bestjev 소개', aboutJev: 'Jev 소개', categories: '범주', projectCategories: '프로젝트 범주', collaborate: '제출 및 협업', collaborateLabel: '제출 및 협업', submit: '제출', email: '이메일', promote: '프로젝트 홍보', open: '탐색 열기', language: '언어' },
  hero: { title: '최고의 Jev 프로젝트', summary: (p, c, l) => `${p}개의 검증된 저장소를 ${c}개 범주와 ${l}개 언어별로 검색하세요.`, lastUpdated: '최종 업데이트', updatedDate: '2026년 9월 20일', filterLanguage: '언어로 필터링', allLanguages: '모든 언어', languages: '언어', searchPlaceholder: '프로젝트, 언어 또는 판단 검색', imageAlt: '구조화된 입력이 Jev를 통해 확률적 판단으로 변환됩니다' },
  catalog: { all: '전체', project: '프로젝트', stars: '스타', language: '언어', description: '설명', projectsLabel: 'Jev 프로젝트', sortAscending: '스타 오름차순 정렬', sortDescending: '스타 내림차순 정렬', noMatches: '일치하는 프로젝트가 없습니다', noMatchesHint: '다른 키워드나 범주를 시도하세요.', showMore: '더 보기' },
  siteIntro: { eyebrow: '카탈로그 소개', title: 'bestjev란?', paragraphs: ['bestjev는 TypeSafe AI의 타입 기반 의사결정용 System One 모델인 Jev를 중심으로 한 독립적인 커뮤니티 관리 오픈소스 프로젝트 디렉터리입니다.', '각 항목은 원본 저장소로 연결되며 범주, 주요 개발 언어, GitHub 스타 스냅샷, 현지화된 설명을 기록합니다. 개발자는 검증 가능한 Jev SDK, 에이전트, 통합, 애플리케이션, 연구 및 도구를 찾을 수 있습니다.', 'bestjev는 TypeSafe AI와 제휴 관계가 없으며 공식적인 보증을 받지 않았습니다.'] },
  about: { title: 'Jev란?', paragraphs: ['Jev는 소프트웨어가 직접 사용할 수 있는 판단을 위한 TypeSafe AI의 System One 모델입니다. 자유 형식 문장 대신 상태와 타입이 지정된 질문을 받아 교정된 확률을 포함한 구조화된 답을 반환합니다.', '선택지나 평가 기준이 미리 정해진 에이전트 라우팅, 도구 호출 검증, 후보 순위 지정, 정책 검사 및 작업 진행 여부 판단에 적합합니다.'], advantage: '운영상의 이점', advantageText: '애플리케이션은 결정적 임계값을 설정하고 불확실성을 확인하며 신뢰도가 낮은 사례를 사람이나 더 큰 모델로 전달할 수 있습니다.', primitives: [{ code: 'CHOICE', title: '하나의 옵션 선택', description: '알려진 집합에서 선택하고 신뢰도와 확률을 반환합니다.' }, { code: 'SCORE', title: '기준에 따라 평가', description: '입력을 순서가 있는 척도에 배치하고 전체 분포를 반환합니다.' }, { code: 'NOUL', title: '진실성 추정', description: '진술이 참일 확률을 0에서 1 사이로 반환합니다.' }] },
  methodology: { title: '이 카탈로그는 어떻게 검증하나요?', intro: '각 항목은 상위 저장소, 프로젝트 문서 및 확인 가능한 Jev 사용 증거와 비교합니다. 스타 수는 특정 날짜의 탐색 스냅샷이며 품질 순위가 아닙니다.', curatedBy: '큐레이션', quote: '“Jev를 비정형 상태를 입력받아 타입이 있는 확률적 판단을 출력하는 프론티어 지능 함수 호출로 생각할 수 있습니다.”', quoteSource: 'TypeSafe AI, Jev 소개', sourcesTitle: 'bestjev는 어떤 소스를 사용하나요?', officialDocs: 'Jev 공식 문서', officialDocsSuffix: ': 제품 개념과 기본 기능.', repositories: '공개 GitHub 저장소', repositoriesSuffix: ': 구현 증거와 메타데이터.', catalogData: '기계 판독 가능한 카탈로그 데이터', catalogDataSuffix: ': 재현 가능한 프로젝트 기록.' },
  submission: { eyebrow: '기여하기', title: '새 프로젝트를 제출하는 방법', intro: 'Jev를 사용하는 공개 프로젝트를 알고 있다면 저장소와 검증 가능한 근거를 보내 주세요. 모든 제출 항목은 카탈로그에 게시되기 전에 검토됩니다.', shortCta: '제출', cta: '프로젝트 제출', ctaHint: '미리 작성된 GitHub Issue가 열립니다.', steps: [{ title: '저장소 공유', description: '공개 GitHub 저장소 URL과 프로젝트가 하는 일을 간단히 알려 주세요.' }, { title: 'Jev 사용 근거 제시', description: 'Jev 통합을 확인할 수 있는 코드, 문서, 데모 또는 기타 공개 자료 링크를 추가해 주세요.' }, { title: '검토 후 게시', description: '근거를 확인하고 적절한 범주를 선택한 뒤 승인된 프로젝트를 향후 카탈로그 업데이트에 추가합니다.' }] },
  footer: { label: '사이트 정보', about: '소개', contact: '문의', privacy: '개인정보', terms: '이용약관', docs: 'Jev 문서' },
};

export default ko;
