import en, { type Messages } from './en';

const ptBr: Messages = {
  ...en,
  seo: { title: (n) => `${n} projetos, SDKs e ferramentas de IA Jev | Awesome Jev`, description: (n) => `Explore ${n} projetos open source, SDKs, agentes, integrações, benchmarks e ferramentas criados em torno do Jev, o modelo System One da TypeSafe AI.`, catalogName: 'Catálogo de projetos open source Awesome Jev', alternateName: 'Catálogo de projetos Awesome Jev', imageAlt: (p, c) => `${p} projetos Jev open source verificados em ${c} categorias` },
  nav: { close: 'Fechar navegação', primary: 'Navegação principal', overview: 'Visão geral', allProjects: 'Todos os projetos', aboutJev: 'Sobre o Jev', categories: 'Categorias', projectCategories: 'Categorias de projetos', collaborate: 'Enviar e colaborar', collaborateLabel: 'Enviar e colaborar', submit: 'Enviar', email: 'E-mail', promote: 'Promova seu projeto', open: 'Abrir navegação', language: 'Idioma' },
  hero: { title: 'Os melhores projetos Jev', summary: (p, c, l) => `Pesquise em ${p} repositórios verificados de ${c} categorias e ${l} linguagens.`, lastUpdated: 'Última atualização', updatedDate: '20 de setembro de 2026', filterLanguage: 'Filtrar por linguagem', allLanguages: 'Todas as linguagens', languages: 'Linguagens', searchPlaceholder: 'Buscar projetos, linguagens ou decisões', imageAlt: 'Entradas estruturadas passam pelo Jev e se tornam decisões probabilísticas' },
  catalog: { all: 'Todos', project: 'Projeto', stars: 'Estrelas', language: 'Linguagem', description: 'Descrição', projectsLabel: 'Projetos Jev', sortAscending: 'Ordenar por estrelas em ordem crescente', sortDescending: 'Ordenar por estrelas em ordem decrescente', noMatches: 'Nenhum projeto encontrado', noMatchesHint: 'Tente outra palavra-chave ou categoria.', showMore: 'Mostrar mais projetos' },
  about: { title: 'O que é o Jev?', paragraphs: ['Jev é o modelo System One da TypeSafe AI para decisões que o software precisa consumir. Em vez de gerar texto livre, ele recebe um estado e perguntas tipadas e retorna respostas estruturadas com probabilidades calibradas.', 'Ele se encaixa em fluxos onde as opções ou critérios são conhecidos previamente: rotear um agente, validar uma chamada de ferramenta, classificar candidatos, verificar uma política ou decidir se uma ação deve continuar.'], advantage: 'Vantagem operacional', advantageText: 'As aplicações podem definir limites determinísticos, inspecionar a incerteza e encaminhar casos de baixa confiança para uma pessoa ou um modelo maior.', primitives: [{ code: 'CHOICE', title: 'Escolher uma opção', description: 'Seleciona de um conjunto conhecido e retorna probabilidades com confiança.' }, { code: 'SCORE', title: 'Avaliar por critérios', description: 'Posiciona uma entrada em uma escala ordenada e retorna a distribuição completa.' }, { code: 'NOUL', title: 'Estimar a verdade', description: 'Retorna a probabilidade de uma afirmação ser verdadeira, de zero a um.' }] },
  methodology: { title: 'Como este catálogo é verificado?', intro: 'Cada item é verificado com evidências públicas: o repositório original, a documentação do projeto e o uso visível do Jev. As estrelas são um retrato datado de descoberta, não um ranking de qualidade.', curatedBy: 'Curadoria de', quote: '“Pense no Jev como uma chamada de função com inteligência de fronteira: estado não estruturado entra, decisões probabilísticas tipadas saem.”', quoteSource: 'TypeSafe AI, apresentação do Jev', sourcesTitle: 'Quais fontes o Awesome Jev utiliza?', officialDocs: 'Documentação oficial do Jev', officialDocsSuffix: ' para conceitos e primitivas do produto.', repositories: 'Repositórios públicos do GitHub', repositoriesSuffix: ' para evidências de implementação e metadados.', catalogData: 'Dados do catálogo legíveis por máquina', catalogDataSuffix: ' para registros de projetos reproduzíveis.' },
  footer: { label: 'Informações do site', about: 'Sobre', contact: 'Contato', privacy: 'Privacidade', terms: 'Termos', docs: 'Documentação do Jev' },
};

export default ptBr;
